name: project_xmedit
description: An XML editing tool.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  collection: ^1.18.0
  file_picker: ^10.3.3
  path: ^1.9.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  window_manager: ^0.5.1
  xml: ^6.5.0
  bitsdojo_window: ^0.1.5 
  url_launcher: ^6.3.2
  uuid: ^4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  msix: ^3.16.12

flutter:
  uses-material-design: true
  assets:
    - assets/code_descriptions.json
    - assets/icd10.json
