name: Draft Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Extract Version
        id: version
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | cut -d ' ' -f 2 | cut -d '+' -f 1)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      
      - name: Create Draft Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          draft: true
          prerelease: false

  build-windows:
    needs: prepare-release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      
      - name: Enable Desktop
        run: flutter config --enable-windows-desktop

      - run: flutter pub get

      - name: Build Windows
        run: flutter build windows --release

      - name: Compress
        run: Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath "${{ needs.prepare-release.outputs.version }}-Windows-x64.zip"

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ needs.prepare-release.outputs.version }} "${{ needs.prepare-release.outputs.version }}-Windows-x64.zip" --clobber

  build-web:
    needs: prepare-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - run: flutter pub get
      
      - name: Setup Web Binaries
        run: dart run sqflite_common_ffi_web:setup

      - name: Build Web
        run: flutter build web --release

      - name: Compress
        run: zip -r "${{ needs.prepare-release.outputs.version }}-Web.zip" build/web

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ needs.prepare-release.outputs.version }} "${{ needs.prepare-release.outputs.version }}-Web.zip" --clobber
